server:
  port: 8082
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sbootintro_db
    username: db_user
    password: db_password

  security:
    user:
      name: name
      password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true


      hocam dersin sonunda hatalari duzeltirken kaydi durdurmasak hatalar da cozumleri de cok degerli